import Foundation

enum StarterVocabulary {
    static let Entries: [WordEntry] = [
        .init(Term: "logging", Translation: "ağac kəsimi"),
        .init(Term: "array", Translation: "sıra; düzüm"),
        .init(Term: "environment", Translation: "ətraf mühit"),
        .init(Term: "habitat", Translation: "yaşayış mühiti"),
        .init(Term: "pollution", Translation: "çirklənmə"),
        .init(Term: "extend", Translation: "uzatmaq; genişləndirmək"),
        .init(Term: "fell", Translation: "ağacı kəsmək", Definition: "To cut down a tree."),
        .init(Term: "nutrients", Translation: "qida maddələri"),
        .init(Term: "terrestrial", Translation: "quruda yaşayan; yerüstü"),
        .init(Term: "aquatic", Translation: "suda yaşayan; suya aid"),
        .init(Term: "vanish", Translation: "yoxa çıxmaq"),
        .init(Term: "myriad", Translation: "saysız-hesabsız"),
        .init(Term: "intact", Translation: "zədəsiz; toxunulmamış"),
        .init(Term: "intercept", Translation: "qarşısını kəsmək"),
        .init(Term: "stabilize", Translation: "sabitləşdirmək"),
        .init(Term: "erosion", Translation: "eroziya; aşınma"),
        .init(Term: "vegetation", Translation: "bitki örtüyü"),
        .init(Term: "inhibit", Translation: "mane olmaq; ləngitmək"),
        .init(Term: "defense", Translation: "müdafiə"),
        .init(Term: "deforestation", Translation: "meşəsizləşmə"),
        .init(Term: "migration", Translation: "köç; miqrasiya"),
        .init(Term: "inhabit", Translation: "məskunlaşmaq"),
        .init(Term: "fascinate", Translation: "heyran etmək; valeh etmək"),
        .init(Term: "imperative", Translation: "vacib; zəruri"),
        .init(Term: "evolve", Translation: "təkamül etmək; inkişaf etmək"),
        .init(Term: "breed", Translation: "çoxalmaq; nəsil artırmaq"),
        .init(Term: "optimal", Translation: "ən əlverişli"),
        .init(Term: "hemisphere", Translation: "yarımkürə"),
        .init(Term: "species", Translation: "növ"),
        .init(Term: "windswept", Translation: "küləyin təsirinə məruz qalmış"),
        .init(Term: "endure", Translation: "dözmək"),
        .init(Term: "fuel", Translation: "yanacaq; gücləndirmək"),
        .init(Term: "aspect", Translation: "cəhət"),
        .init(Term: "feat", Translation: "nailiyyət; uğur"),
        .init(Term: "nocturnal", Translation: "gecə fəal olan"),
        .init(Term: "obscure", Translation: "naməlum; qaranlıq"),
        .init(Term: "starry", Translation: "ulduzlu"),
        .init(Term: "diurnal", Translation: "gündüz fəal olan"),
        .init(Term: "navigation", Translation: "istiqamət tapma; naviqasiya"),
        .init(Term: "occupy", Translation: "tutmaq; məskunlaşmaq"),
        .init(Term: "sparse", Translation: "seyrək"),
        .init(Term: "swing", Translation: "yellənmək; dəyişmək"),
        .init(Term: "violent", Translation: "şiddətli"),
        .init(Term: "extreme", Translation: "həddindən artıq; ifrat"),
        .init(Term: "transitional", Translation: "keçid dövrünə aid"),
        .init(Term: "fringe", Translation: "kənar; haşiyə"),
        .init(Term: "diverse", Translation: "müxtəlif"),
        .init(Term: "adapt", Translation: "uyğunlaşmaq"),
        .init(Term: "thrive", Translation: "inkişaf etmək"),
        .init(Term: "resilient", Translation: "dözümlü; dayanıqlı"),
        .init(Term: "stressor", Translation: "stress yaradan amil"),
        .init(Term: "minimize", Translation: "minimuma endirmək"),
        .init(Term: "moisture", Translation: "rütubət; nəmlik"),
        .init(Term: "prolific", Translation: "məhsuldar; çox nəsil verən"),
        .init(Term: "mechanisms", Translation: "mexanizmlər"),
        .init(Term: "evaporation", Translation: "buxarlanma"),
        .init(Term: "dilute", Translation: "seyrəltmək"),
        .init(Term: "determine", Translation: "müəyyən etmək"),
        .init(Term: "accumulate", Translation: "yığılmaq; toplamaq")
    ]
}
