// <auto-generated />
using HRManagementApp.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagementApp.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504084629_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagementApp.Core.Entities.Department", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SalaryLimit")
                        .HasColumnType("float");

                    b.Property<int>("WorkerLimit")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Name = "IT",
                            SalaryLimit = 25000.0,
                            WorkerLimit = 10
                        },
                        new
                        {
                            Name = "HR",
                            SalaryLimit = 10000.0,
                            WorkerLimit = 5
                        },
                        new
                        {
                            Name = "Marketing",
                            SalaryLimit = 12000.0,
                            WorkerLimit = 8
                        });
                });

            modelBuilder.Entity("HRManagementApp.Core.Entities.Employee", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("No");

                    b.HasIndex("DepartmentName");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            No = "IT1001",
                            DepartmentName = "IT",
                            FullName = "Samir Həsənov",
                            Position = "Senior Backend Developer",
                            Salary = 3500.0
                        },
                        new
                        {
                            No = "IT1002",
                            DepartmentName = "IT",
                            FullName = "Leyla Əliyeva",
                            Position = "Frontend Developer",
                            Salary = 2000.0
                        },
                        new
                        {
                            No = "HR1003",
                            DepartmentName = "HR",
                            FullName = "Vüqar Kərimov",
                            Position = "HR Specialist",
                            Salary = 1500.0
                        },
                        new
                        {
                            No = "MA1004",
                            DepartmentName = "Marketing",
                            FullName = "Nigar Rüstəmova",
                            Position = "Marketing Manager",
                            Salary = 2500.0
                        });
                });

            modelBuilder.Entity("HRManagementApp.Core.Entities.Employee", b =>
                {
                    b.HasOne("HRManagementApp.Core.Entities.Department", null)
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRManagementApp.Core.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
